# TODO: Either use or remove these
graphql:
  servlet:
#    mapping: /graphql
#    enabled: true
#    corsEnabled: true
    exception-handlers-enabled: true
#    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    websocket:
      enabled: false